<template>
  <div>
    <DataTable :value="tableData" striped-rows removableSort>
      <Column field="name" header="Field name" sortable style="max-width: 8rem;">
        <template #body="slotProps">
            <div class="flex items-center gap-2 min-w-0 overflow-hidden">
              <span class="truncate block" v-tooltip.left="displayKey(slotProps.data.name)">{{ displayKey(slotProps.data.name) }}</span>
            </div>
        </template>
      </Column>
      <Column header="Value">
        <template #body="slotProps">
          <div class="flex items-center gap-2">
            <InputText v-if="slotProps.data.result" v-model="slotProps.data.result.value" class="w-full min-w-[200px]" />
            <Button 
              v-if="isEdited(slotProps.data)"
              severity="secondary"
              text
              rounded
              class="shrink-0 !p-1"
              aria-label="Reset"
              v-tooltip.top="'Discard changes'"
              @click="resetRow(slotProps.data)"
            >
              <Undo :size="16" />
            </Button>
          </div>
        </template>
      </Column>
      <Column field="result.confidence" header="Confidence" sortable style="width: 3rem;">
        <template #body="slotProps">
          <span v-if="isEdited(slotProps.data)" class="text-gray-300">
            ---
          </span>
          <template v-else-if="isBelowThreshold(slotProps.data)">
            <div class="flex flex-row gap-2">
              <ArrowDownFromLine :size="20" class="text-orange-700" />
            </div>
          </template>
          <template v-else-if="slotProps.data.result && typeof slotProps.data.result.confidence === 'number' && slotProps.data.result.value">
            <span
              :class="[
                'w-2.5 h-2.5 rounded-full inline-block mr-2 align-middle',
                confidenceClass(slotProps.data.result.confidence)
              ]"
            ></span>
            <span class="text-sm">{{ Math.round(slotProps.data.result.confidence * 100) }}%</span>
          </template>
          <span v-else class="text-gray-300">
            ---
          </span>
        </template>
      </Column>
      <Column field="strategy" header="" sortable style="width: 2rem">
        <template #body="slotProps">
          <Tag v-if="slotProps.data.strategy == 'Contextual'" severity="warn">
            <Bot v-tooltip.top="'This value was generated by a context-aware LLM.'" :size="16" />
          </Tag>
        </template>
      </Column>
    </DataTable>
  </div>
</template>

<script lang="ts" setup>
import { ArrowDownFromLine, Bot, CircleAlert, Undo } from '@lucide/vue';
import { ref, watch } from 'vue';
import { Tag, Button, DataTable, Column, InputText } from 'primevue';
import type { ProcessedFields } from '~~/shared/types/workers';

const props = defineProps<{
  fields: ProcessedFields
  minConfidence?: number
}>()

const tableData = ref<any[]>([])

watch(() => props.fields, (newFields) => {
  if (!newFields) {
    tableData.value = []
    return
  }
  tableData.value = Object.entries(newFields).map(([name, value]: [string, any]) => {
    return {
      ...value,
      name: name,
      _originalValue: value.result ? value.result.value : null
    }
  })
}, { immediate: true })

const resetRow = (rowData: any) => {
  if (rowData.result) {
    rowData.result.value = rowData._originalValue
  }
}

const isEdited = (rowData: any) => {
  if (!rowData.result) return false;
  return rowData.result.value !== rowData._originalValue;
}

const displayKey = (key: string) => {
  let toReturn = key;
  if (key.includes('.')) {
    toReturn = key.split('.')[1]!
  }

  return capitaliseFirst(toReturn)
}

const confidenceClass = (confidence: number) => {
  // between 0 and 1
  if (!isFinite(confidence) || confidence <= 0) return 'bg-gray-400'

  if (confidence >= 0.85) return 'bg-green-600'
  if (confidence >= 0.6) return 'bg-amber-500'
  if (confidence >= 0.4) return 'bg-orange-500'
  return 'bg-red-500'
}

const hasValue = (value: any) => {
  if (value === null || value === undefined) return false
  if (Array.isArray(value)) return value.length > 0
  if (typeof value === 'string') return value.trim().length > 0
  return true
}

const isBelowThreshold = (rowData: any) => {
  if (!rowData?.result) return false
  if (isEdited(rowData)) return false
  if (!hasValue(rowData.result.value)) return false

  const min = props.minConfidence ?? 0
  if (!isFinite(min) || min <= 0) return false
  const confidence = rowData.result.confidence
  if (typeof confidence !== 'number') return false
  return confidence < min
}
</script>

<style></style>