<template>
  <div>
    <DataTable :value="tableData" striped-rows removableSort>
      <Column field="name" header="Field name" sortable>
        <template #body="slotProps">
            {{ displayKey(slotProps.data.name) }}
        </template>
      </Column>
      <Column header="Value">
        <template #body="slotProps">
            {{ slotProps.data.result.value }}
        </template>
      </Column>
      <Column field="result.confidence" header="Confidence" sortable>
        <template #body="slotProps">
          <template v-if="slotProps.data.result && slotProps.data.result.value">
            <span
              :class="[
                'w-2.5 h-2.5 rounded-full inline-block mr-2 align-middle',
                confidenceClass(slotProps.data.result.confidence)
              ]"
            ></span>
            <span class="text-sm">{{ Math.round(slotProps.data.result.confidence * 100) }}%</span>
          </template>
          <span v-else class="text-gray-300">
            ---
          </span>
        </template>
      </Column>
      <Column field="strategy" header="" sortable>
        <template #body="slotProps">
          <Tag v-if="slotProps.data.strategy == 'Contextual'" severity="warn">
            <Bot v-tooltip.top="'This value was generated by a context-aware LLM.'" :size="16" />
          </Tag>
        </template>
      </Column>
    </DataTable>
  </div>
</template>

<script lang="ts" setup>
import { Bot } from '@lucide/vue';
import type { ProcessedFields } from '~~/shared/types/workers';

const props = defineProps<{
  fields: ProcessedFields
}>()


const tableData = computed(() => {
  return Object.entries(props.fields).map(([name, value]) => {
  return {
    ...value,
    name: name
  }
})
})

const displayKey = (key: string) => {
  let toReturn = key;
  if (key.includes('.')) {
    toReturn = key.split('.')[1]!
  }

  return capitaliseFirst(toReturn)
}

const capitaliseFirst = (val: string) => {
  return String(val).charAt(0).toUpperCase() + String(val).slice(1);
}

const confidenceClass = (confidence: number) => {
  // between 0 and 1
  if (!isFinite(confidence) || confidence <= 0) return 'bg-gray-400'

  if (confidence >= 0.85) return 'bg-green-600'
  if (confidence >= 0.6) return 'bg-amber-500'
  if (confidence >= 0.4) return 'bg-orange-500'
  return 'bg-red-500'
}
</script>

<style></style>